### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'dist'

### ISSUE THREAD

**Issue by yochananmarqos** [micahflee/torbrowser-launcher#446]
After upgrading Python to 3.8 on Manjaro GNOME, I'm receiving this error with the `setup.py`:

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    distro = platform.dist()[0]
AttributeError: module 'platform' has no attribute 'dist'
```

**Comment by Qwertylex** [comment]
same as you but on archlinux

**Comment by AsciiWolf** [comment]
Same issue when trying to [build](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/pull/13) Tor Browser Launcher Flatpak using a new runtime. The platform.dist() function [seems to be](https://www.google.com/search?q=python+platform.dist+deprecated) deprecated.

/cc @micahflee

**Comment by kpcyrd** [comment]
I think this has been fixed in 212876a1d4d1e8cefed6d4f2e2cbe2933cf0412f
