### PR TITLE
Remove use of deprecated platform.dist() (fixes #446)

### LINKED ISSUE #446: AttributeError: module 'platform' has no attribute 'dist'
After upgrading Python to 3.8 on Manjaro GNOME, I'm receiving this error with the `setup.py`:

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    distro = platform.dist()[0]
AttributeError: module 'platform' has no attribute 'dist'
```

### PR DESCRIPTION
**Pull request by milkey-mouse**
platform.dist was deprecated a while ago and finally removed in Python 3.8. It was only used for a workaround for issue #128 (and #215) which is no longer necessary, so just remove the use altogether.

This broke the build for me with the Gentoo overlay, which upgraded to Python 3.8 recently.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Could this PR be updated so @micahflee can merge it?

**Comment by milkey-mouse** [comment]
done

**Comment by yardenac** [comment]
I guess this is probably a better patch than https://github.com/micahflee/torbrowser-launcher/pull/444
